blank_issues_enabled: false

contact_links:
  - name: Gift of Open Source Discussion
    url: https://pantheon-community.slack.com/
    about: You can ask questions or discuss the Gift of Open Source 2021 challenge here.